export const CFG = {
  maxMessages: 5000,
  excerptChars: 400,
  tooltipMaxChars: 80,
  repulsion: 9000,
  spring: 0.05,
  springLen: 90,
  damping: 0.85,
  centerPull: 0.002,
  minR: 3,
  maxR: 20,
  pulseFreq: 2.0,
  clickTolerancePx: 4,
  hitPad: 4,
  toolNodeScale: 0.6,
  fitPadding: 0.85,
  prewarmIterations: 180,
  zoomStep: 1.1,
  zoomMin: 0.1,
  zoomMax: 8,
  birthDurationMs: 600,
  birthSpreadMin: 0.7,
  birthSpreadMax: 1.0,
  birthAlphaStart: 0.25,
  birthRadiusStart: 0.5,
  // Auto-degrade пороги — при большом графе отключаем дорогие эффекты
  perfDegradeThreshold: 400,   // выше — режим "performance"
  perfHeavyThreshold: 1500,    // выше — совсем минимализм
  perfMinimalParticles: 0,     // 0 = отключить частицы
  perfMinimalStarCount: 80,
  perfMinimalPrewarm: 40,
  perfMinimalTypewriter: false,
  perfMinimalPhysicsSkip: 2,   // в minimal — физика раз в 2 кадра
  perfMinimalAlphaDecay: 0.06, // быстрее остывает, меньше work до settle
  perfDegradedPhysicsSkip: 1,  // degraded — каждый кадр (как обычно)

  // v3 wow
  edgeCurveStrength: 0.18,
  particleSpeed: 0.5,
  particlesPerEdge: 1,
  particleSize: 1,
  particleTrailLen: 4,
  particleTrailGap: 0.02,
  particleJitterPx: 1.8,
  particleHaloMul: 2.2,
  particleMidMul: 1.4,
  particleFlashChance: 0.04,
  particleFlashMul: 1.4,
  edgeFlashChance: 0.0012,
  edgeFlashDurationMs: 100,
  edgeFlashLineWidth: 0.9,
  heartbeatAmplitude: 0.005,
  heartbeatFreq: 0.35,
  starfieldCount: 400,
  starDepthMin: 0.1,
  starDepthMax: 0.5,
  starWorldRange: 3000,
  storyFadeMs: 260,
  storyMaxChars: 360,
  storyDwellMs: 1600,
  storyMaxHistory: 40,
  storyCharMs: 22,
  storyMaxTypeMs: 1300,
  toolUseTsStepMs: 300,
  toolIconMinR: 6,
  toolIconMinFontPx: 9,
  toolIconFontMul: 1.25,
  nodeGlowRadiusMul: 1.9,
  nodeGlowAlphaBase: 0.08,
  nodeGlowAlphaPulse: 0.04,
  nodeGlowInnerStop: 0.4,
  searchDimAlpha: 0.22,
  searchPulseFreq: 3.5,
  livePollMs: 800,
  liveReconnectMs: 2500,
  minimapW: 170,
  minimapH: 110,
  minimapEveryNFrames: 3,
  minimapNodeR: 1.3,
  minimapPadding: 8,
  radialRingGap: 130,
  layoutTransitionMs: 900,
  barnesHutThreshold: 300,
  barnesHutTheta: 0.9,
  bhLeafMinSize: 1.0,
  // Physics v5 — D3-style cooling + clamps
  alphaDecay: 0.0228,     // ≈ (1 − 0.001^(1/300)) — settles за ~300 iters
  alphaMin: 0.001,
  velocityDecay: 0.4,     // "friction": vx *= (1 − velocityDecay)
  reheatAlpha: 0.3,
  maxVelocity: 40,
  repulsionCutoff: 3500,       // выше — дальние кластеры всё ещё отталкиваются
  wallStiffness: 0.02,         // мягче — стена не формирует прямоугольник
  wallPaddingMul: 8,           // дальше — почти не виден bbox
  centerPullScaleN: 200,       // centerPull растёт как sqrt(N/200)
  leafSpringBoost: 2.5,        // spring для degree-1 edges в 2.5× сильнее (root/leaf не отрываются)
  playSpeedOptions: [0.5, 1, 2, 5],
  storyPostGapMs: 800,
  focusDimAlpha: 0.3,
  cameraFollowLerp: 0.05,
  cameraTargetLerp: 0.15,
  zoomOnClickFactor: 1.8,
  useGradientFillBelow: 250,
};

export const COLORS = {
  bg: '#0a0e1a',
  user: '#7BAAF0',
  assistant: '#50D4B5',
  tool: '#ECA040',
  edge: 'rgba(0, 212, 255, 0.35)',
  toolEdge: 'rgba(236, 160, 64, 0.45)',
  accent: '#ECA040',
  text: '#cfe6ff',
  muted: '#6a7c95',
  particle: 'rgba(140, 230, 255, ',
  star: 'rgba(200, 220, 255, ',
};
